spring:
  application:
    name: quartz
  
  quartz:
    auto-startup: true
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
    job-store-type: 
      memory